## 数据集相关操作
### 创建一个CSV数据集
这里涉及到：
* 创建目录
* 在指定目录创建某文件
* 打开某文件并写入内容

In [2]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)   # 创建上级目录中名为"data"的文件夹，若存在则不报错。
data_file = os.path.join('..', 'data', 'house_tiny.csv') # ..' 表示当前目录的上一级目录。 'data' 是上一级目录下的一个子目录名。 'house_tiny.csv' 是最终要指向的具体文件的名称。
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')   # 列名
    f.write('NA,Pave,127500\n')         # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

### 读取CSV数据集

In [3]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

### 将Data处理为inputs与outputs

In [4]:
inputs = data.iloc[:, 0:2]  # 所有行，0~1 列
outputs = data.iloc[:, 2]   # 所有行  2 列

inputs

   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN

### 处理缺失值NAN
> 注意，“NaN”项代表缺失值。为了处理缺失的数据，典型的方法包括插值法和删除法。这里我们考虑插值法：

#### 对连续性数据插入均值

对于$Alley$列，由于都是字符串。所以不会对缺失值进行均值插入。故最终受影响的只是$NumRooms$列

In [7]:
inputs = inputs.fillna(inputs.mean())

#### 对离散型数据进行独热编码

In [9]:
inputs = pd.get_dummies(inputs, dummy_na=True,dtype=int )
# print(inputs)
inputs

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1